server:
  port: 8040
spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      #抽样率
      probability: 1.0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: gateway
        namespace: 0f1188c0-c978-4c16-afc9-5d92c085b4bd
    gateway:
      discovery:
        locator:
          #gateway自动去nacos读取微服务配置
          enabled: true
      routes:
        - id: user_route
          uri: lb://user-center
          predicates:
            - Path=/users/**
        - id: center_route
          uri: lb://content-center
          predicates:
            - Path=/shares/**,/admin/shares/**


#  profiles:
#    active: 11-Self
management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
